// Code generated by gen_tls.go; DO NOT EDIT.
package v1

import "crypto/tls"

// --- CIPHER MAPPINGS ---

// CipherToID maps IANA cipher suite names to Go crypto/tls cipher IDs.
// Only includes TLS 1.2+ ciphers supported by Go's crypto/tls package.
// Use this for Go servers to translate user-provided IANA names to Go IDs.
var CipherToGoId = map[string]uint16{
	"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256":       49195,
	"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384":       49196,
	"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": 52393,
	"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":         49199,
	"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":         49200,
	"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256":   52392,
}

// CipherToOpenSSL maps IANA cipher suite names to OpenSSL cipher names.
// Only includes TLS 1.2+ ciphers (modern and intermediate profiles).
// Use this for C++/OpenSSL servers to translate user-provided IANA names to OpenSSL names.
var CipherToOpenSSL = map[string]string{
	"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256":       "ECDHE-ECDSA-AES-128-GCM-SHA256",
	"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384":       "ECDHE-ECDSA-AES-256-GCM-SHA384",
	"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
	"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":         "ECDHE-RSA-AES-128-GCM-SHA256",
	"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":         "ECDHE-RSA-AES-256-GCM-SHA384",
	"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256":   "ECDHE-RSA-CHACHA20_POLY1305",
}

// --- GROUP MAPPINGS ---

// GroupToGoId maps group/curve names to Go crypto/tls curve IDs.
// Includes standard curves and post-quantum hybrid groups.
// Use this for Go servers to translate user-provided group names to Go IDs.
var GroupToGoId = map[string]uint16{
	"SecP256r1MLKEM768":  4587,
	"SecP384r1MLKEM1024": 4589,
	"X25519":             29,
	"X25519MLKEM768":     4588,
	"prime256v1":         23,
	"secp256r1":          23,
	"secp384r1":          24,
	"secp521r1":          25,
}

// GroupToOpenSSL maps group/curve names to OpenSSL group names.
// Use this for C++/OpenSSL servers to translate user-provided group names to OpenSSL names.
var GroupToOpenSSL = map[string]string{
	"SecP256r1MLKEM768":  "SecP256r1MLKEM768",
	"SecP384r1MLKEM1024": "SecP384r1MLKEM1024",
	"X25519":             "x25519",
	"X25519MLKEM768":     "X25519MLKEM768",
	"prime256v1":         "prime256v1",
	"secp256r1":          "prime256v1",
	"secp384r1":          "secp384r1",
	"secp521r1":          "secp521r1",
}

// --- VERSION MAPPINGS ---

// VersionToID maps TLS version strings to Go crypto/tls version IDs.
var VersionToGoId = map[string]uint16{
	"TLSv1.2": tls.VersionTLS12,
	"TLSv1.3": tls.VersionTLS13,
}

// VersionToOpenSSL maps TLS version strings to OpenSSL version names.
var VersionToOpenSSL = map[string]string{
	"TLSv1.2": "TLSv1.2",
	"TLSv1.3": "TLSv1.3",
}
