//go:build ignore

package main

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"
)

type MozillaJSON struct {
	Configurations map[string]struct {
		Ciphers struct {
			IANA []string `json:"iana"`
		} `json:"ciphers"`
		TLSCurves   []string `json:"tls_curves"`
		TLSVersions []string `json:"tls_versions"`
	} `json:"configurations"`
}

var groupToGoID = map[string]uint16{
	"prime256v1":         uint16(tls.CurveP256),
	"secp256r1":          uint16(tls.CurveP256), // Alias for prime256v1 (P-256)
	"secp384r1":          uint16(tls.CurveP384),
	"secp521r1":          uint16(tls.CurveP521),
	"X25519":             uint16(tls.X25519),
	"X25519MLKEM768":     uint16(tls.X25519MLKEM768),
	"SecP256r1MLKEM768":  uint16(tls.SecP256r1MLKEM768),
	"SecP384r1MLKEM1024": uint16(tls.SecP384r1MLKEM1024),
}

var groupToOpenSSL = map[string]string{
	"prime256v1":         "prime256v1",
	"secp256r1":          "prime256v1", // OpenSSL uses prime256v1
	"secp384r1":          "secp384r1",
	"secp521r1":          "secp521r1",
	"X25519":             "x25519",
	"X25519MLKEM768":     "X25519MLKEM768",
	"SecP256r1MLKEM768":  "SecP256r1MLKEM768",
	"SecP384r1MLKEM1024": "SecP384r1MLKEM1024",
}

func main() {
	data, err := os.ReadFile("tls_config.json")
	if err != nil {
		fmt.Println("Error: tls_config.json not found. Run 'make sync-tls' first.")
		os.Exit(1)
	}

	var moz MozillaJSON
	if err := json.Unmarshal(data, &moz); err != nil {
		panic(err)
	}

	// Only use modern and intermediate profiles (TLS 1.2+), skip "old" profile
	supportedCiphers := make(map[string]bool)
	uniqueGroups := make(map[string]bool)

	for profile, cfg := range moz.Configurations {
		// Skip "old" profile which includes TLS 1.0/1.1
		if profile == "old" {
			continue
		}

		for _, c := range cfg.Ciphers.IANA {
			// Only include ciphers supported by Go (TLS 1.2+)
			if cipherToGoId(c) != 0 {
				supportedCiphers[c] = true
			}
		}

		for _, r := range cfg.TLSCurves {
			uniqueGroups[r] = true
		}
	}

	// Add hybrid groups and aliases that may not be in Mozilla's JSON yet
	for group := range groupToGoID {
		uniqueGroups[group] = true
	}

	// Setup Template functions
	funcMap := template.FuncMap{
		"cipherToGoId": cipherToGoId,
		"cipherToOpenSSL": func(iana string) string {
			if strings.Contains(iana, "_AES_") && !strings.Contains(iana, "_WITH_") {
				return iana
			}
			if strings.Contains(iana, "CHACHA20") {
				return strings.ReplaceAll(strings.ReplaceAll(iana, "TLS_ECDHE_RSA_WITH_", "ECDHE-RSA-"), "_SHA256", "")
			}
			res := strings.ReplaceAll(iana, "TLS_", "")
			res = strings.ReplaceAll(res, "_WITH_", "_")
			return strings.ReplaceAll(res, "_", "-")
		},
		"groupToGoId": func(name string) uint16 { return groupToGoID[name] },
		"groupToOpenSSL": func(name string) string {
			if val, ok := groupToOpenSSL[name]; ok {
				return val
			}
			return strings.ToLower(name)
		},
		"sort": func(m map[string]bool) []string {
			keys := make([]string, 0, len(m))
			for k := range m {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			return keys
		},
	}

	// Generate the code
	f, err := os.Create("mappings_generated.go")
	if err != nil {
		fmt.Println("Error: failed to generate mappings")
		os.Exit(1)
	}
	defer f.Close()

	tmpl := template.Must(template.New("tls").Funcs(funcMap).Parse(fileTemplate))
	tmpl.Execute(f, map[string]interface{}{
		"Ciphers": supportedCiphers,
		"Groups":  uniqueGroups,
	})
}

func cipherToGoId(iana string) uint16 {
	for _, s := range append(tls.CipherSuites(), tls.InsecureCipherSuites()...) {
		if s.Name == iana {
			return s.ID
		}
	}
	return 0
}

const fileTemplate = `// Code generated by gen_tls.go; DO NOT EDIT.
package v1

import "crypto/tls"

// --- CIPHER MAPPINGS ---

// CipherToID maps IANA cipher suite names to Go crypto/tls cipher IDs.
// Only includes TLS 1.2+ ciphers supported by Go's crypto/tls package.
// Use this for Go servers to translate user-provided IANA names to Go IDs.
var CipherToGoId = map[string]uint16{
{{- range sort .Ciphers }}
	"{{ . }}": {{ cipherToGoId . }},
{{- end }}
}

// CipherToOpenSSL maps IANA cipher suite names to OpenSSL cipher names.
// Only includes TLS 1.2+ ciphers (modern and intermediate profiles).
// Use this for C++/OpenSSL servers to translate user-provided IANA names to OpenSSL names.
var CipherToOpenSSL = map[string]string{
{{- range sort .Ciphers }}
	"{{ . }}": "{{ cipherToOpenSSL . }}",
{{- end }}
}

// --- GROUP MAPPINGS ---

// GroupToGoId maps group/curve names to Go crypto/tls curve IDs.
// Includes standard curves and post-quantum hybrid groups.
// Use this for Go servers to translate user-provided group names to Go IDs.
var GroupToGoId = map[string]uint16{
{{- range sort .Groups }}
	"{{ . }}": {{ groupToGoId . }},
{{- end }}
}

// GroupToOpenSSL maps group/curve names to OpenSSL group names.
// Use this for C++/OpenSSL servers to translate user-provided group names to OpenSSL names.
var GroupToOpenSSL = map[string]string{
{{- range sort .Groups }}
	"{{ . }}": "{{ groupToOpenSSL . }}",
{{- end }}
}

// --- VERSION MAPPINGS ---

// VersionToID maps TLS version strings to Go crypto/tls version IDs.
var VersionToGoId = map[string]uint16{
	"TLSv1.2": tls.VersionTLS12,
	"TLSv1.3": tls.VersionTLS13,
}

// VersionToOpenSSL maps TLS version strings to OpenSSL version names.
var VersionToOpenSSL = map[string]string{
	"TLSv1.2": "TLSv1.2",
	"TLSv1.3": "TLSv1.3",
}
`
